# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman", "~>3.3.12"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]

# Taken from https://robots.thoughtbot.com/middleman-bourbon-walkthrough
# These will make the site a bit better looking, and I need all the help
# I can get!
gem 'bitters'
gem 'bourbon'
gem 'neat'

gem "bootstrap-sass", :require => false
